* Inbox
** [2022-03-22 Tue 12:09] Problem with two rocks at exact same pos causes infinite recursion building the Tree

** [2022-03-20 Sun 16:47] TreeNode Testing

280 ms for 100 reps of 10000 with original getchild
230 ms with fasr getchild - decided not to do
185 ms by removing reserve capacity! (because not every node needs children..)
Arena testing took 470ms!!!! This was using a common storage 
vector that was not reallocated on each build cycle. Interesting
that this was so much slower. See arenapass branch.

** [2022-03-14 Mon 20:33] Gravity Over Accel
Another issue: at very small distances (sub radius), forces get really high
When then sign flips due to collision system, get crazy high accelerations
This is causing the "exploding" particles problem.
Fixed with check for distance < radius combined

[[file:~/projects/gravity/src/world.cpp][file:~/projects/gravity/src/world.cpp]]

** [2022-03-13 Sun 19:13] Perf Results
On linux, running around 8fps with 2000 rocks (12 on mac??)
Heaviest hit is Atan2 using about 40% of samples
SinCos is next highest @ 33 

Now running with fast @ 49 fps on mac @ 2000 rocks!
On desktop, running 59fps @ 2000 rocks!!

35 fps now on mac with hypot, switched back and back at 45 fps.

using the combined system, running at same speed as before. Did not help.

inlining now have 2000 @ 57fps on mac, 27 fps @ 3000 rocks on mac

with first par, now @ 47fps @ 3000!
using temp for vel counter now @ 53 fps @ 3000!
with using just acc instead of vel inner look @ 55fps @ 3000 on mac
on linux, running at 59fps flat @ 3000. Top bottleneck has shifted to isColliding.

